apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  # This defind which pods are going to be represented by this Service
  # The service become a network endpoint for either other services
  selector:
    app: webapp
    release: "0-5"

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  selector:
    app: activemq

  ports:
    - name: http
      port: 8161
      nodePort: 30010

  type: NodePort
